 Sun, 22 Mar 2020 21:18:00  INFO test_purset.py setUpClass [ line:42 ] ==================== 准备开始执行添加发票信息接口测试 ====================
 Sun, 22 Mar 2020 21:18:00  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/auth/login，请求参数：{'phone': '15733100728', 'code': '123456'}
 Sun, 22 Mar 2020 21:18:00  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/purchaser-setting，请求参数：{'name': 'oCV77s', 'duty_paragraph': '1122', 'address': '单位地址', 'phone': '15733100728', 'bank_name': '开户行', 'card_no': '1234'}
 Sun, 22 Mar 2020 21:18:01  INFO test_purset.py test_purset [ line:87 ] 预期结果是：{'code': 200, 'msg': 'ok', 'data': True}，实际结果是：{'code': 200, 'msg': 'ok', 'data': True}，测试通过
 Sun, 22 Mar 2020 21:18:01  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/auth/login，请求参数：{'phone': '15733100728', 'code': '123456'}
 Sun, 22 Mar 2020 21:18:01  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/purchaser-setting，请求参数：{'name': '4H2TBS', 'duty_paragraph': '1122', 'address': '单位地址', 'phone': '15733100728', 'bank_name': '开户行', 'card_no': '1234'}
 Sun, 22 Mar 2020 21:18:01  ERROR test_purset.py test_purset [ line:82 ]  :: {'code': 200, 'data': True, 'msg': 'ok'} != {'code': 500, 'data': '', 'msg': '收票单位重复'}
Traceback (most recent call last):
  File "/Applications/software/PyCharm.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'code': 200, 'msg': 'ok', 'data': True} != {'code': 500, 'msg': '收票单位重复', 'data': ''}
- {'code': 200, 'data': True, 'msg': 'ok'}
?          ^            ^^^^          ^^

+ {'code': 500, 'data': '', 'msg': '收票单位重复'}
?          ^            ^^          ^^^^^^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yangli/PycharmProjects/api_fsctest/util/test_purset.py", line 79, in test_purset
    self.assertEqual(res, eval(case.expected_data))
  File "/Applications/software/PyCharm.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 38, in _patched_equals
    raise error
teamcity.diff_tools.EqualsAssertionError:  :: {'code': 200, 'data': True, 'msg': 'ok'} != {'code': 500, 'data': '', 'msg': '收票单位重复'}
 Sun, 22 Mar 2020 21:18:02  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/auth/login，请求参数：{'phone': '15733100728', 'code': '123456'}
 Sun, 22 Mar 2020 21:18:02  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/purchaser-setting，请求参数：{'name': '', 'duty_paragraph': '333'}
 Sun, 22 Mar 2020 21:18:02  INFO test_purset.py test_purset [ line:87 ] 预期结果是：{"code":422,"msg":"\u8bf7\u8f93\u5165\u6536\u7968\u5355\u4f4d"}，实际结果是：{'code': 422, 'msg': '请输入收票单位'}，测试通过
 Sun, 22 Mar 2020 21:18:02  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/auth/login，请求参数：{'phone': '15733100728', 'code': '123456'}
 Sun, 22 Mar 2020 21:18:03  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/purchaser-setting，请求参数：{'name': 'pZn7eS', 'duty_paragraph': ''}
 Sun, 22 Mar 2020 21:18:03  ERROR test_purset.py test_purset [ line:82 ]  :: {'code': 200, 'data': True, 'msg': 'ok'} != {'code': 422, 'msg': '请输入收票单位'}
Traceback (most recent call last):
  File "/Applications/software/PyCharm.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'code': 200, 'msg': 'ok', 'data': True} != {'code': 422, 'msg': '请输入收票单位'}
- {'code': 200, 'data': True, 'msg': 'ok'}
+ {'code': 422, 'msg': '请输入收票单位'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yangli/PycharmProjects/api_fsctest/util/test_purset.py", line 79, in test_purset
    self.assertEqual(res, eval(case.expected_data))
  File "/Applications/software/PyCharm.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 38, in _patched_equals
    raise error
teamcity.diff_tools.EqualsAssertionError:  :: {'code': 200, 'data': True, 'msg': 'ok'} != {'code': 422, 'msg': '请输入收票单位'}
 Sun, 22 Mar 2020 21:18:03  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/auth/login，请求参数：{'phone': '15733100728', 'code': '123456'}
 Sun, 22 Mar 2020 21:18:04  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/purchaser-setting，请求参数：{'name': ' ', 'duty_paragraph': '555'}
 Sun, 22 Mar 2020 21:18:05  INFO test_purset.py test_purset [ line:87 ] 预期结果是：{"code":422,"msg":"\u8bf7\u8f93\u5165\u6536\u7968\u5355\u4f4d"}，实际结果是：{'code': 422, 'msg': '请输入收票单位'}，测试通过
 Sun, 22 Mar 2020 21:18:05  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/auth/login，请求参数：{'phone': '15733100728', 'code': '123456'}
 Sun, 22 Mar 2020 21:18:05  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/purchaser-setting，请求参数：{'name': '# name', 'duty_paragraph': ' '}
 Sun, 22 Mar 2020 21:18:05  ERROR test_purset.py test_purset [ line:82 ]  :: {'code': 200, 'data': True, 'msg': 'ok'} != {'code': 422, 'msg': '请输入收票单位'}
Traceback (most recent call last):
  File "/Applications/software/PyCharm.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'code': 200, 'msg': 'ok', 'data': True} != {'code': 422, 'msg': '请输入收票单位'}
- {'code': 200, 'data': True, 'msg': 'ok'}
+ {'code': 422, 'msg': '请输入收票单位'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yangli/PycharmProjects/api_fsctest/util/test_purset.py", line 79, in test_purset
    self.assertEqual(res, eval(case.expected_data))
  File "/Applications/software/PyCharm.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 38, in _patched_equals
    raise error
teamcity.diff_tools.EqualsAssertionError:  :: {'code': 200, 'data': True, 'msg': 'ok'} != {'code': 422, 'msg': '请输入收票单位'}
 Sun, 22 Mar 2020 21:18:05  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/auth/login，请求参数：{'phone': '15733100728', 'code': '123456'}
 Sun, 22 Mar 2020 21:18:06  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/purchaser-setting，请求参数：{'name': '# name', 'duty_paragraph': ' 777'}
 Sun, 22 Mar 2020 21:18:06  ERROR test_purset.py test_purset [ line:82 ]  :: {'code': 500, 'data': '', 'msg': '收票单位重复'} != {'code': 200, 'data': True, 'msg': 'ok'}
Traceback (most recent call last):
  File "/Applications/software/PyCharm.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'code': 500, 'msg': '收票单位重复', 'data': ''} != {'code': 200, 'msg': 'ok', 'data': True}
- {'code': 500, 'data': '', 'msg': '收票单位重复'}
?          ^            ^^          ^^^^^^

+ {'code': 200, 'data': True, 'msg': 'ok'}
?          ^            ^^^^          ^^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yangli/PycharmProjects/api_fsctest/util/test_purset.py", line 79, in test_purset
    self.assertEqual(res, eval(case.expected_data))
  File "/Applications/software/PyCharm.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 38, in _patched_equals
    raise error
teamcity.diff_tools.EqualsAssertionError:  :: {'code': 500, 'data': '', 'msg': '收票单位重复'} != {'code': 200, 'data': True, 'msg': 'ok'}
 Sun, 22 Mar 2020 21:18:06  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/auth/login，请求参数：{'phone': '15733100728', 'code': '123456'}
 Sun, 22 Mar 2020 21:18:07  INFO http_request.py request [ line:39 ] 正在发送请求，请求地址：https://fsc-test.manshang.com/api/purchaser-setting，请求参数：{'name': '56546n', 'duty_paragraph': '888', 'address': '单位地址', 'phone': '15733100728', 'bank_name': '开户行', 'card_no': '1234'}
 Sun, 22 Mar 2020 21:18:07  INFO test_purset.py tearDownClass [ line:48 ] ==================== 添加发票信息测试执行完毕 ====================
